Repository apiaryio/api-elements.js, pull requests merged in 2019-02, with the labels that each got.

#140 Remove use of process.nextTick in OAS 2 parser
  packages/fury-adapter-swagger/CHANGELOG.md
  packages/fury-adapter-swagger/lib/parser.js
Labels: openapi2

#147 fix(oas3): validate required for path parameter
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseOperationObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseParameterObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseParameterObjects-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parsePathItemObject-test.js
Labels: openapi3

#58 Use Drafter 4
  packages/fury-adapter-apib-parser/CHANGELOG.md
  packages/fury-adapter-apib-parser/lib/adapter.js
  packages/fury-adapter-apib-parser/package.json
  packages/fury-adapter-apib-parser/test/adapter-test.js
  packages/fury-adapter-apib-parser/test/validate-test.js
  yarn.lock
Labels: apiblueprint, do not merge

#149 Parsing headers (including HeadersObject)
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/STATUS.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseComponentsObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseHeaderObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseResponseObject.js
  packages/fury-adapter-oas3-parser/lib/parser/parseMap.js
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.sourcemap.json
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseComponentsObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseHeaderObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseResponseObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/parseMap-test.js
Labels: openapi3

#142 Never return an error and a result
  packages/fury-adapter-apiary-blueprint-parser/lib/parser.js
  packages/fury-adapter-apiary-blueprint-parser/test/adapter-test.js
  packages/fury-adapter-swagger/lib/parser.js
  packages/fury-adapter-swagger/test/adapter-test.js
  packages/fury-adapter-swagger/test/inherit-parameters-test.js
  packages/fury/CHANGELOG.md
  packages/fury/lib/fury.js
  packages/fury/test/fury-test.js
  packages/fury/test/validate-test.js
Labels: core

#156 Added partial support for the `example` in Parameter Object
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseParameterObject-test.js
Labels: openapi3

#150 valueOf method for EnumElement
  packages/minim-api-description/CHANGELOG.md
  packages/minim-api-description/lib/api-description.js
  packages/minim-api-description/lib/define-value-of.js
  packages/minim-api-description/test/value-of-test.js
Labels: core

#161 Support number status codes in Responses Object
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseResponsesObject.js
  packages/fury-adapter-oas3-parser/lib/predicates.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseResponsesObject-test.js
Labels: openapi3

#160 Warn for invalid 'Parameter Object' 'in'
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseParameterObject-test.js
Labels: openapi3

#163 Release fury-adapter-oas3-parser 0.5.2
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/package.json
Labels: openapi3

#168 Update minim to 0.23.0
  packages/api-elements/package.json
  packages/fury-cli/package.json
  packages/fury/CHANGELOG.md
  packages/fury/package.json
  packages/minim-api-description/package.json
  packages/minim-parse-result/package.json
  yarn.lock
Labels: core

#170 Fix handling of !!map and !!set for empty values
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/parseYAML.js
  packages/fury-adapter-oas3-parser/test/unit/parser/parseYAML-test.js
Labels: openapi3

#172 Release fury 3.0.0-beta.9
  packages/fury-adapter-apiary-blueprint-parser/CHANGELOG.md
  packages/fury-adapter-apiary-blueprint-parser/package.json
  packages/fury-adapter-apib-parser/CHANGELOG.md
  packages/fury-adapter-apib-parser/package.json
  packages/fury-adapter-apib-serializer/CHANGELOG.md
  packages/fury-adapter-apib-serializer/package.json
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/package.json
  packages/fury-adapter-swagger/CHANGELOG.md
  packages/fury-adapter-swagger/package.json
  packages/fury-cli/CHANGELOG.md
  packages/fury-cli/package.json
  packages/fury/CHANGELOG.md
  packages/fury/package.json
Labels: core

#174 Make release dates consistent with other packages
  packages/fury-adapter-oas3-parser/CHANGELOG.md
Labels: openapi3
