Repository apiaryio/api-elements.js, pull requests merged in 2019-04, with the labels that each got.

#185 Add support for oauth2 in the OAS 3 parser
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOauthFlowObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOauthFlowsObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseSecuritySchemeObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseOauthFlowObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseOauthFlowsObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parsePathItemObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseSecuritySchemeObject-test.js
Labels: openapi3

#208 Handle invalid security scheme components
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseComponentsObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseComponentsObject-test.js
Labels: bug, openapi3

#210 Improve YAML error message descriptions
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/parseYAML.js
  packages/fury-adapter-oas3-parser/test/unit/parser/parseYAML-test.js
Labels: openapi3

#213 feat(oas3): validate parameter name according to location
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseOperationObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseParameterObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parsePathItemObject-test.js
Labels: openapi3

#214 Klokane/handle malformed query
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseParameterObject-test.js
Labels: openapi3

#215 fix(oas3): redefine path name allowed chars
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseParameterObject-test.js
Labels: openapi3

#216 Release fury-adapter-oas3-parser 0.7.4
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/package.json
  packages/fury-cli/package.json
Labels: openapi3

#221 Handle invalid schema object examples in OAS 2
  packages/fury-adapter-swagger/CHANGELOG.md
  packages/fury-adapter-swagger/lib/json-schema.js
  packages/fury-adapter-swagger/package.json
  packages/fury-adapter-swagger/test/fixtures/schema-references-example-invalid.json
  packages/fury-adapter-swagger/test/fixtures/schema-references-example-invalid.yaml
  packages/fury-cli/package.json
Labels: openapi2
