Repository apiaryio/api-elements.js, pull requests merged in 2019-06, with the labels that each got.

#237 Add regression fixture for json body with array[object]
  packages/fury-adapter-swagger/CHANGELOG.md
  packages/fury-adapter-swagger/lib/generator.js
  packages/fury-adapter-swagger/package.json
  packages/fury-adapter-swagger/test/fixtures/json-body-generation-array-object.json
  packages/fury-adapter-swagger/test/fixtures/json-body-generation-array-object.yaml
  packages/fury-adapter-swagger/test/generator-test.js
  yarn.lock
Labels: bug, openapi2

#240 Ensure test expectations cause failure
  packages/fury-adapter-remote/test/fury-test.js
Labels: remote

#238 Remove reference to unused minim-api-description
  packages/api-elements/package.json
Labels: core

#241 Rename minim option as namespace
  packages/fury-adapter-apiary-blueprint-parser/lib/parser.js
  packages/fury-adapter-oas3-parser/lib/adapter.js
  packages/fury-adapter-remote/lib/adapter.js
  packages/fury-adapter-swagger/lib/generator.js
  packages/fury-adapter-swagger/lib/headers.js
  packages/fury-adapter-swagger/lib/link.js
  packages/fury-adapter-swagger/lib/parser.js
  packages/fury-adapter-swagger/test/generator-test.js
  packages/fury-adapter-swagger/test/parameter-test.js
  packages/fury-adapter-swagger/test/parser-test.js
  packages/fury/CHANGELOG.md
  packages/fury/lib/fury.js
  packages/fury/test/parse-test.js
  packages/fury/test/serialize-test.js
  packages/fury/test/validate-test.js
Labels: core

#245 Support async/await (and promises)
  packages/fury/CHANGELOG.md
  packages/fury/README.md
  packages/fury/lib/fury.js
  packages/fury/test/assert.js
  packages/fury/test/parse-test.js
  packages/fury/test/serialize-test.js
  packages/fury/test/validate-test.js
Labels: core

#248 feat(oas3): support parameters in media types
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseMediaTypeObject.js
  packages/fury-adapter-oas3-parser/package.json
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseMediaTypeObject-test.js
Labels: openapi3
