Repository apiaryio/api-elements.js, pull requests merged in 2019-01, with the labels that each got.

#85 Update links to OAS 3 issues
  packages/fury-adapter-oas3-parser/README.md
  packages/fury-adapter-oas3-parser/STATUS.md
  packages/fury-adapter-oas3-parser/package.json
Labels: openapi3

#86 Schema Object parser should not accept member
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseComponentsObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOpenAPIObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseSchemaObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseSchemaObject-test.js
Labels: openapi3

#87 Support schema in Media Type Object
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseMediaTypeObject.js
  packages/fury-adapter-oas3-parser/test/integration/fixtures/components/path-item-object-parameters.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.json
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseMediaTypeObject-test.js
Labels: openapi3

#90 Move validating object into parseObject
  packages/fury-adapter-oas3-parser/lib/parser/annotations.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseComponentsObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseInfoObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseMediaTypeObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOpenAPIObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOperationObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObjects.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parsePathItemObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseReferenceObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseRequestBodyObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseResponseObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseResponsesObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseSchemaObject.js
  packages/fury-adapter-oas3-parser/lib/parser/parseObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/parseObject-test.js
Labels: openapi3

#93 Support OpenAPI 3 in Fury CLI
  packages/fury-cli/lib/fury.js
  packages/fury-cli/package.json
Labels: cli, openapi3

#102 Warn on and ignore non-unique `operationId`
  packages/fury-adapter-oas3-parser/lib/parser/annotations.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOperationObject.js
  packages/fury-adapter-oas3-parser/lib/state.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseOperationObject-test.js
Labels: openapi3

#91 feat(oas3): support description in response object
  packages/fury-adapter-oas3-parser/STATUS.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseResponseObject.js
  packages/fury-adapter-oas3-parser/test/integration/fixtures/components/path-item-object-parameters.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.json
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseResponseObject-test.js
Labels: openapi3

#99 Mention OAS 3 parser in README
  README.md
Labels: openapi3

#107 Update Sphinx docs to work with monorepository and pipenv
  .circleci/config.yml
  README.md
  docs/Pipfile
  docs/Pipfile.lock
  docs/conf.json
  docs/conf.py
  docs/requirements.txt
  package.json
  packages/minim-api-description/lib/elements/category.js
  yarn.lock
Labels: docs

#106 Fixing fury-adapter-apib-serializer link
  README.md
Labels: docs

#115 Fix incorrect test path for path item parser
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parsePathItemObject-test.js
Labels: openapi3

#117 Mention OAS 3 in fury-cli README
  packages/fury-cli/README.md
Labels: cli

#116 Emit warnings for unsupported properties in Parameter Object
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObject.js
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.json
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseParameterObject-test.js
Labels: openapi3

#114 Support operation parameters
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/STATUS.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOperationObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parsePathItemObject.js
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.sourcemap.json
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseOperationObject-test.js
Labels: openapi3

#113 Refactor parseObject to handle required keys validations
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/annotations.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseComponentsObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseInfoObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOpenAPIObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOperationObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseReferenceObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseResponseObject.js
  packages/fury-adapter-oas3-parser/lib/parser/openapi.js
  packages/fury-adapter-oas3-parser/lib/parser/parseObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseParameterObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/parseObject-test.js
Labels: openapi3

#121 Don't emit errors for missing path parameters
  packages/fury-adapter-oas3-parser/lib/parser/oas/parsePathItemObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parsePathItemObject-test.js
Labels: openapi3

#123 Release fury-adapter-oas3-parser 0.4.1
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/package.json
Labels: openapi3

#125 Support referencing sub schemas
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseComponentsObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseReferenceObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseSchemaObject.js
  packages/fury-adapter-oas3-parser/lib/parser/parseReference.js
  packages/fury-adapter-oas3-parser/test/integration/fixtures/components/media-type-object-schema.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/components/media-type-object-schema.yaml
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseSchemaObject-test.js
Labels: openapi3

#129 Support required property in schema object
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/STATUS.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseSchemaObject.js
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.sourcemap.json
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseSchemaObject-test.js
Labels: openapi3

#131 Detect openapi version string without quotes
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/adapter.js
  packages/fury-adapter-oas3-parser/test/unit/adapter-test.js
Labels: openapi3

#119 Skip rendering column/line numbers in non-annotation source maps
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOpenAPIObject.js
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.sourcemap.json
Labels: openapi3

#134 Release fury-cli 0.8.9
  packages/fury-cli/CHANGELOG.md
  packages/fury-cli/package.json
Labels: cli

#112 Prefer example values when generating body in OAS 2
  packages/fury-adapter-swagger/CHANGELOG.md
  packages/fury-adapter-swagger/lib/generator.js
  packages/fury-adapter-swagger/package.json
Labels: openapi2

#136 Rename result variable to parseResult
  packages/fury-adapter-oas3-parser/lib/parser/parseReference.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseComponentsObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseInfoObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseMediaTypeObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseOpenAPIObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseOperationObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseParameterObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseParameterObjects-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parsePathItemObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parsePathsObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseReferenceObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseRequestBodyObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseResponseObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseResponsesObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseSchemaObject-test.js
Labels: openapi3
