Repository apiaryio/api-elements.js, pull requests merged in 2019-03, with the labels that each got.

#176 Support referencing properties in data structures
  packages/fury-adapter-swagger/CHANGELOG.md
  packages/fury-adapter-swagger/lib/schema.js
  packages/fury-adapter-swagger/test/schema-test.js
Labels: openapi2

#177 refactor(oas3): added parseArray predicate
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseSchemaObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseSecurityRequirementObject.js
  packages/fury-adapter-oas3-parser/lib/parser/parseArray.js
  packages/fury-adapter-oas3-parser/lib/parser/parseObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseSecurityRequirementObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/parseArray-test.js
Labels: openapi3

#178 Don't duplicate property descriptions on member
  packages/fury-adapter-swagger/CHANGELOG.md
  packages/fury-adapter-swagger/lib/schema.js
  packages/fury-adapter-swagger/test/schema-test.js
  packages/swagger-zoo/fixtures/features/api-elements/recursion.json
  packages/swagger-zoo/fixtures/features/api-elements/recursion.sourcemap.json
Labels: openapi2

#179 Fix serialising message payload without headers
  packages/fury-adapter-apib-serializer/CHANGELOG.md
  packages/fury-adapter-apib-serializer/lib/filters.js
  packages/fury-adapter-apib-serializer/test/filters-test.js
Labels: apiblueprint

#182 No longer catch exceptions throw by adapters
  commitlint.config.js
  packages/fury/CHANGELOG.md
  packages/fury/lib/fury.js
  packages/fury/test/fury-test.js
Labels: core

#183 Add JSDoc comments to Fury
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseComponentsObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseHeaderObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseInfoObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseMediaTypeObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOpenAPIObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOperationObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObjects.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parsePathItemObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parsePathsObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseReferenceObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseRequestBodyObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseResponseObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseResponsesObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseSchemaObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseSecurityRequirementObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseSecuritySchemeObject.js
  packages/fury-adapter-oas3-parser/lib/parser/parseArray.js
  packages/fury-adapter-oas3-parser/lib/parser/parseBoolean.js
  packages/fury-adapter-oas3-parser/lib/parser/parseCopy.js
  packages/fury-adapter-oas3-parser/lib/parser/parseMap.js
  packages/fury-adapter-oas3-parser/lib/parser/parseObject.js
  packages/fury-adapter-oas3-parser/lib/parser/parseString.js
  packages/fury-adapter-oas3-parser/lib/pipeParseResult.js
  packages/fury-adapter-oas3-parser/lib/predicates.js
  packages/fury-adapter-swagger/lib/adapter.js
  packages/fury-adapter-swagger/lib/json-schema.js
  packages/fury/lib/fury.js
Labels: docs

#187 Parse "Example Object" in OAS 3
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/STATUS.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseComponentsObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseExampleObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseMediaTypeObject.js
  packages/fury-adapter-oas3-parser/test/integration/components-test.js
  packages/fury-adapter-oas3-parser/test/integration/fixtures/components/media-type-object-examples.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/components/media-type-object-examples.yaml
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseComponentsObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseExampleObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseMediaTypeObject-test.js
Labels: openapi3

#191 Support generating message body from schema
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseMediaTypeObject.js
  packages/fury-adapter-oas3-parser/test/integration/fixtures/components/operation-object-requestBody.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/components/path-item-object-parameters-unsupported-parameter.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/components/path-item-object-parameters.json
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseMediaTypeObject-test.js
Labels: openapi3

#192 fix(core): method is propagated form fury to `adapter.dectect()`
  packages/fury/lib/fury.js
  packages/fury/test/fury-test.js
Labels: core

#194 Fix handling of invalid schema components
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseComponentsObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOpenAPIObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseComponentsObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseOpenAPIObject-test.js
Labels: bug, openapi3

#193 Fix handling of YAML errors while scanning for next token in OAS 3
  packages/fury-adapter-oas3-parser/lib/parser/parseYAML.js
  packages/fury-adapter-oas3-parser/test/unit/parser/parseYAML-test.js
Labels: bug, openapi3

#195 Support header parameters
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/STATUS.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOperationObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parsePathItemObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseOperationObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseParameterObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parsePathItemObject-test.js
Labels: openapi3

#196 Referenced data structures are now correct type
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseReferenceObject.js
  packages/fury-adapter-oas3-parser/test/integration/fixtures/components/media-type-object-schema.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.sourcemap.json
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseReferenceObject-test.js
Labels: openapi3

#197 Handle pre-parsing object members in parseObject
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseComponentsObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOpenAPIObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseSecuritySchemeObject.js
  packages/fury-adapter-oas3-parser/lib/parser/parseObject.js
Labels: openapi3

#198 Support generating body from schema with references
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseComponentsObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseMediaTypeObject.js
  packages/fury-adapter-oas3-parser/test/integration/fixtures/components/media-type-object-schema.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/components/responses-object-response-with-schema.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.sourcemap.json
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseMediaTypeObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseResponseObject-test.js
  packages/minim-api-description/lib/define-value-of.js
  packages/minim-api-description/test/value-of-test.js
Labels: openapi3

#201 Export the remote adapter class
  packages/fury-adapter-remote/lib/adapter.js
  packages/fury-adapter-remote/test/fury-test.js
Labels: remote

#199 fix(remote): use mediatype from Fury
  packages/fury-adapter-remote/README.md
  packages/fury-adapter-remote/lib/adapter.js
  packages/fury-adapter-remote/test/fury-test.js
Labels: remote
