Repository apiaryio/api-elements.js, pull requests merged in 2020-04, with the labels that each got.

#432 Marco/oas3 server variable
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseSchemaObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseServerObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseServerVariableObject.js
  packages/fury-adapter-oas3-parser/lib/parser/parseEnum.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseServerObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseServerVariableObject-test.js
Labels: openapi3

#435 Add support for OAS 3 default responses
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/STATUS.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseResponsesObject.js
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.json
  packages/fury-adapter-oas3-parser/test/integration/fixtures/petstore.sourcemap.json
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseResponsesObject-test.js
Labels: enhancement, openapi3

#430 Update Info Object status in OAS 3
  packages/fury-adapter-oas3-parser/STATUS.md
Labels: openapi3

#438 Use Protagonist / drafter.js directly
  packages/fury-adapter-apib-parser/lib/adapter.js
  packages/fury-adapter-apib-parser/package.json
  yarn.lock
Labels: apiblueprint

#447 Support explode query parameters
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/STATUS.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseOperationObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObject.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseParameterObjects.js
  packages/fury-adapter-oas3-parser/lib/parser/oas/parsePathItemObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseOperationObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseParameterObject-test.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parsePathItemObject-test.js
Labels: openapi3

#455 Rename apib-serializer
  .circleci/smoke.sh
  README.md
  packages/apib-serializer/CHANGELOG.md
  packages/apib-serializer/README.md
  packages/apib-serializer/lib/adapter.js
  packages/apib-serializer/lib/filters.js
  packages/apib-serializer/lib/mson.js
  packages/apib-serializer/package.json
  packages/apib-serializer/template.nunjucks
  packages/apib-serializer/test/adapter-test.js
  packages/apib-serializer/test/filters-test.js
  packages/apib-serializer/test/fixtures/action.apib
  packages/apib-serializer/test/fixtures/action.json
  packages/apib-serializer/test/fixtures/basic.apib
  packages/apib-serializer/test/fixtures/basic.json
  packages/apib-serializer/test/fixtures/data-structure.apib
  packages/apib-serializer/test/fixtures/data-structure.json
  packages/apib-serializer/test/fixtures/description.apib
  packages/apib-serializer/test/fixtures/description.json
  packages/apib-serializer/test/fixtures/headers.apib
  packages/apib-serializer/test/fixtures/headers.json
  packages/apib-serializer/test/fixtures/metadata.apib
  packages/apib-serializer/test/fixtures/metadata.json
  packages/apib-serializer/test/fixtures/parameters-no-value.apib
  packages/apib-serializer/test/fixtures/parameters-no-value.json
  packages/apib-serializer/test/fixtures/request-only.apib
  packages/apib-serializer/test/fixtures/request-only.json
  packages/apib-serializer/test/fixtures/resource-attributes.apib
  packages/apib-serializer/test/fixtures/resource-attributes.json
  packages/apib-serializer/test/fixtures/resource-group.apib
  packages/apib-serializer/test/fixtures/resource-group.json
  packages/apib-serializer/test/fixtures/resource-without-group.apib
  packages/apib-serializer/test/fixtures/resource-without-group.json
  packages/apib-serializer/test/fixtures/resource.apib
  packages/apib-serializer/test/fixtures/resource.json
  packages/apib-serializer/test/fixtures/sample.apib
  packages/apib-serializer/test/fixtures/sample.json
  packages/apib-serializer/test/fixtures/transaction.apib
  packages/apib-serializer/test/fixtures/transaction.json
  packages/apib-serializer/test/mson-test.js
  packages/fury-cli/lib/fury.js
  packages/fury-cli/package.json
Labels: apiblueprint

#457 Handle missing variables in Server Object url
  packages/openapi3-parser/CHANGELOG.md
  packages/openapi3-parser/lib/parser/oas/parseServerObject.js
  packages/openapi3-parser/package.json
  packages/openapi3-parser/test/unit/parser/oas/parseServerObject-test.js
Labels: openapi3
