Repository apiaryio/api-elements.js, pull requests merged in 2020-01, with the labels that each got.

#395 Prevent installing yarn on CI
  .circleci/config.yml
Labels: bug

#394 Emit node tag in error for unsupported tag
  packages/fury-adapter-oas3-parser/lib/parser/parseYAML.js
Labels: openapi3

#397 fix(packages/fury-adapter-remote): implements `generateSourceMap`
  packages/fury-adapter-remote/CHANGELOG.md
  packages/fury-adapter-remote/lib/adapter.js
  packages/fury-adapter-remote/test/fury-test.js
Labels: remote

#404 Warn for unsupported scheme
  packages/fury-adapter-oas3-parser/CHANGELOG.md
  packages/fury-adapter-oas3-parser/lib/parser/oas/parseSecuritySchemeObject.js
  packages/fury-adapter-oas3-parser/test/unit/parser/oas/parseSecuritySchemeObject-test.js
Labels: bug, openapi3
